### ISSUE TITLE
Clean install fail

### ISSUE THREAD

**Issue by MichelDiz** [akveo/kittenTricks#1]
Tryout with Yarn and NPM. Same problem.

> Loading dependency graph, done.
> error: bundling: UnableToResolveError: Unable to resolve module `../setupBabel` from `/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/index.js`: 
> Directory /Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/setupBabel doesn't exist
>     at ResolutionRequest._loadAsDir (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:572:13)
>     at tryResolveSync (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:411:18)
>     at tryResolveSync (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:89:12)
>     at ResolutionRequest._resolveFileOrDir (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:409:12)
>     at ResolutionRequest._resolveNodeDependency (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:417:19)
>     at ResolutionRequest.resolveDependency (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:135:29)
>     at dependencyNames.map.name (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:59)
>     at Array.map (native)
>     at ResolutionRequest.resolveModuleDependencies (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:42)
>     at module.readFresh.then (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:182:40)
> Bundling `index.js`  0.0(0/2), failed.

**Comment by MichelDiz** [comment]
I tried to "npm run restart" kind of it works, but got me another error.
> Loading dependency graph, done.
> error: bundling: UnableToResolveError: Unable to resolve module `wolfy87-eventemitter` from `/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native-ui-kitten/src/styles/themeManager.js`: Module does not exist in the module map or in these directories:
>   /Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native-ui-kitten/node_modules
> ,   /Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules
> 
> This might be related to https://github.com/facebook/react-native/issues/4968
> To resolve try the following:
>   1. Clear watchman watches: `watchman watch-del-all`.
>   2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
>   3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
>     at ResolutionRequest._resolveNodeDependency (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:470:11)
>     at ResolutionRequest.resolveDependency (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:135:29)
>     at dependencyNames.map.name (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:59)
>     at Array.map (native)
>     at ResolutionRequest.resolveModuleDependencies (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:42)
>     at module.readFresh.then (/Volumes/x/Development/2017/Projeto-/kittenTricks/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:182:40)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:169:7)
> Bundling `index.js`  99.7(1153/1155), failed.

**Comment by MichelDiz** [comment]
tomorrow (during the day) I gonna try harder.

**Comment by cllgeek** [comment]
I have the some problem , please fix it , thank you

**Comment by SashaSkywalker** [comment]
@cllgeek, @MichelDiz

instead of ```npm run restart``` you can try run ```npm run start```

**Comment by MichelDiz** [comment]
Gentlemans my problem is solved. I just got time like now:
I deleted the files. 
Clone it again 
and "Yarn install" 
and then React-native run-android.

I think someone fixed it.

Thank you all.

Best Regards.

PS. AWESOME PROJECT!

**Comment by cllgeek** [comment]
@MichelDiz its worked
