### ISSUE TITLE
Double touch - Navigation should be blocking

### ISSUE THREAD

**Issue by kaminskypavel** [akveo/kittenTricks#10]
kudos! this is a great project.

since screen rendering times may take more than a few milliseconds its tempting to touch twice,
which resolves in a double opening of the screen (see gif attached).

![ezgif-3-5335fb307b](https://user-images.githubusercontent.com/4253088/27774402-58c3fa6a-5f9a-11e7-8969-8546029c3dcf.gif)

**Comment by elupanov** [comment]
Hello @kaminskypavel and thank you! Yes, it is known issue and we are working on it.

**Comment by kaminskypavel** [comment]
Perfect! Kudos again, cool project.

**Comment by nikhilbiju67** [comment]
is there any solutions yet? ;(

**Comment by malashkevich** [comment]
hello @nikhilbiju67.
kittenTricks using `react-navigation` as navigation library.
[There is according issue](https://github.com/react-community/react-navigation/issues/271) in their repository.
There are a lot of ideas on how to fix this behavior.
Hope it helps!
