### ISSUE TITLE
Can't Change Icon

### ISSUE THREAD

**Issue by ngocnvn** [akveo/kittenTricks#11]
https://github.com/akveo/kittenTricks/blob/master/app/assets/icons.js

**Comment by SashaSkywalker** [comment]
Hello @ngocnvn, 

For example I want use this icon http://fontawesome.io/icon/heart/
1. Find unicode of icon 
![screen shot 2017-07-04 at 1 20 11 pm](https://user-images.githubusercontent.com/6690616/27826462-bead584a-60bb-11e7-954f-66bc487fbfa0.png)
2. Then I can add icon as ```heart2: '\uf004',```  it's the same thing as ```heart2:String.fromCharCode(61444),```

I know that changing and adding new icons in app it's a bit complicated process for now, so I think we will refactor it in near future.
