### ISSUE TITLE
Are you planning adding support for typescript/flow?

### ISSUE THREAD

**Issue by pie6k** [akveo/kittenTricks#12]
Yup. In my opinion it's quite useful in larger projects

**Comment by malashkevich** [comment]
Hello @pietrasiak.
Actually we don't have plans to move to typescript.
However it's good idea to support flow. I'll add this to our roadmap.
Thanks for suggestion!

**Comment by pie6k** [comment]
You're welcome ;) for now - it's blocking issue for me to start using this great utility.

**Comment by mdgiles** [comment]
Any news on support for Flow?  Just to see what would happen, I ran "react native init" to create a new app, copied the default .flowconfig into the kittenTricks app , and added the flow designator at the start of app.js:

`// @flow`

Thousands of errors result.  Flow support would be really great.

**Comment by artyorsh** [comment]
Hi guys. Really happy to announce that we've started working on this. Stay tuned 😎
