### ISSUE TITLE
Question: Any interest in putting together a premium version for sale on SugarKubes?

### ISSUE THREAD

**Issue by wrannaman** [akveo/kittenTricks#121]
Hi @akveo-private , congrats on the traction! Would you be interested in putting together a premium version of this RN starter to sell on [SugarKubes](https://sugarkubes.io)? It's a code and container marketplace I'm putting together.

**Comment by tianlinzx** [comment]
@wrannaman  i have paid for your react-native-starter project , but I am not invited yet.
My paid email address is issunion@163.com.

**Comment by wrannaman** [comment]
@tianlinzx Sorry about that! I'll figure out what's going on right now. You can message me at andrew at sugarkubes.io
