### ISSUE TITLE
Demo: Side Menu -> Walkthrough -> [Get Started] = no function

### ISSUE THREAD

**Issue by muescha** [akveo/kittenTricks#14]
### where: 
- Demo iPhone "Kitten Tricks"
- open Side Menu 
- select Walkthrough
- tap on button "Get Startet"

### what i see:
- it does nothing

### what i expect:
- close modal window

### Note
this error is only if come from "Side Menu" (via the hamburger icon or via navigation / side menu )

**Comment by elupanov** [comment]
Hi @muescha, thank you for finding the issue

**Comment by artyorsh** [comment]
fixed with time :)
