### ISSUE TITLE
build(assets): undo expo images optimization

### ISSUE THREAD

**Issue by artyorsh** [akveo/kittenTricks#165]
Compressed images do not look good. Should be replaced with original

**Comment by sergeichestakov** [comment]
Hey @artyorsh,

Have you tried recovering the original images from git? You can also specify the quality by running `expo optimize --quality=80` (default is 60).

Thanks,
Sergei

**Comment by artyorsh** [comment]
Hi @sergeichestakov 

I always try to keep the latest expo-cli on my mac. It looks like the default behavior of some of the expo-cli versions made this issue.

Btw thanks for suggestion. It will help to prevent this issue in a future release. Will try 👍
But for now, seems only recovering images could help
