### ISSUE TITLE
core(navigation): navigation between layouts takes a lot of time

### ISSUE THREAD

**Issue by artyorsh** [akveo/kittenTricks#167]
It's possible to tap twice to perform navigation twice because of delay

**Comment by brentvatne** [comment]
you should use `navigation.navigate` instead of `navigation.push`

**Comment by artyorsh** [comment]
This could be extremely helpful in case we were not [using it](https://github.com/akveo/kittenTricks/blob/master/src/containers/layouts/auth/container/auth.container.tsx#L25) 😄 

Btw currently I have no other idea of why this occurs

**Comment by brentvatne** [comment]
navigation should definitely not be happening twice here then 🤔

**Comment by artyorsh** [comment]
The main trouble of it is that the application freezes when trying to perform navigation to some route (e.g tapping on a list item to route on the details page). During this delay, user can tap any other UI element which will lead to calling `navigation.navigate` one more time
