### ISSUE TITLE
Steps to get the project running

### ISSUE THREAD

**Issue by brentvatne** [akveo/kittenTricks#170]
### Issue type

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
- I cloned the project and ran `yarn` then `yarn start:dev` and the project errors:

```
Error: resolve_projpath: path `/Users/brentvatne/coding/react-native-ui-kitten/src/framework/ui`: open: /Users/brentvatne/coding/react-native-ui-kitten/src/framework/ui: No such file or directory
```

**Expected behavior:**
- Run the project

**Steps to reproduce:**
- Clone the repo, follow the steps described in the `Current behavior` section above

**Related code:**
- No code required

### Other information:

macOS, running in iOS simulator

**Comment by artyorsh** [comment]
Hi @brentvatne. Thanks for report

`start:dev` script is currently used in our team locally to quickly review [UI Kitten](https://github.com/akveo/react-native-ui-kitten) components changes. In case you don't need this, consider using one of the following scripts:
`yarn start` or `yarn start:prod`

This will start the project with production configuration (meaning it will use [UI Kitten](https://github.com/akveo/react-native-ui-kitten) from `node_modules`)
