### ISSUE TITLE
Password input show/Hide button not working

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/kittenTricks#176]
Hi Team,

In IOS your demo application password input show/hide button not working... gif file for reference.

![461E40F2-D487-4A6B-94B5-7B5493232F00](https://user-images.githubusercontent.com/6933841/59425670-03233680-8e09-11e9-84fc-0b6b7b39ffa3.gif)

**Comment by artyorsh** [comment]
This is not rather a bug, but a feature request.
There is no option to handle icon press inside Input. Btw this is a feature we want to add in the future [UI Kitten](https://github.com/akveo/react-native-ui-kitten) release

Thanks for report

**Comment by ImAbhishekTomar** [comment]
@artyorsh Thanks!!! for reply... any target date for new version release? And where I can find about new release and what include in new release.

**Comment by artyorsh** [comment]
We can not announce a target for the new release now, but you can subscribe to the [UI Kitten](https://github.com/akveo/react-native-ui-kitten) repository to stay tuned 👍  
There you can track an actual framework changes and look through some issue discussions
