### ISSUE TITLE
Button Status property is not working

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/kittenTricks#179]
Hi,

I have tried to change button coloraturas using STATUS='WARNING' props but any STATUS props not working please help.

> Not Working : status="warning" with button

**MY CODE**

```
<Button
	style={themedStyle.signInButton}
	textStyle={textStyle.button}
	disabled={!this.state.formData}
	status="warning"
	onPress={this.onSignInButtonPress}
>
	SIGN IN WITH QUIBIK
</Button>
```

**Comment by artyorsh** [comment]
Hi @IAmAbhishekTomar 

What exactly do you mean with "not working"? Do you have any crashes?

I have just tried changing setting `warning` status to the example you have provided and everything works properly
