### ISSUE TITLE
[Article List] Master/Detail view broken on Android

### ISSUE THREAD

**Issue by chreble** [akveo/kittenTricks#18]
Articles don't expand to detail view on `Android`, it works correctly on `iOS` though.

**Comment by elupanov** [comment]
@chreble what is your phone model and andriod version? thank you

**Comment by chreble** [comment]
Galaxy S8 and `Android 7.0`

**Comment by Tibing** [comment]
Hi, @chreble! Could you please clarify what articles screen did you keep in mind?

**Comment by chreble** [comment]
Hi @Tibing, sure thing

Any article from the listing, from `Article List V1` to `V4` or blogposts.
Tapping on images or headlines doesn't trigger transition to the full article.

**Comment by Tibing** [comment]
Thanks for the help, @chreble!  :relaxed:
