### ISSUE TITLE
80% of elements position isn't right !!

### ISSUE THREAD

**Issue by deounix** [akveo/kittenTricks#181]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Text are getting padding-bottom so it's go up

**Expected behavior:**
Text should be viewed correctly

### Other information:

**OS, device, application version **
```
Resolution: 2340x1080
OS: Android 9
Device: huawei p30 pro
```

ScreenShots:

![Screenshot_20190614_195910_com akveo kittenTricks](https://user-images.githubusercontent.com/17798647/59525551-51a30480-8edf-11e9-8dc0-af3a7354bd78.jpg)
![Screenshot_20190614_195921](https://user-images.githubusercontent.com/17798647/59525553-51a30480-8edf-11e9-9d28-ebefeb5089c0.jpg)
![Screenshot_20190614_195146](https://user-images.githubusercontent.com/17798647/59525555-51a30480-8edf-11e9-8ad3-bf91c67c0376.jpg)
![Screenshot_20190614_195209](https://user-images.githubusercontent.com/17798647/59525556-523b9b00-8edf-11e9-927e-3bdf73a8465f.jpg)
![Screenshot_20190614_195658](https://user-images.githubusercontent.com/17798647/59525558-523b9b00-8edf-11e9-87a3-cfbf3dbf34f5.jpg)
![Screenshot_20190614_195712_com akveo kittenTricks](https://user-images.githubusercontent.com/17798647/59525559-523b9b00-8edf-11e9-9f88-306d0f9104f1.jpg)
![Screenshot_20190614_195723](https://user-images.githubusercontent.com/17798647/59525560-52d43180-8edf-11e9-9f63-9f4d1154174c.jpg)
![Screenshot_20190614_195736_com akveo kittenTricks](https://user-images.githubusercontent.com/17798647/59525561-52d43180-8edf-11e9-9cb1-93c08a9037e7.jpg)
![Screenshot_20190614_195753](https://user-images.githubusercontent.com/17798647/59525562-52d43180-8edf-11e9-85c4-379e7edc32ef.jpg)
![Screenshot_20190614_195850_com akveo kittenTricks](https://user-images.githubusercontent.com/17798647/59525564-52d43180-8edf-11e9-92ed-1b393d320240.jpg)
![Screenshot_20190614_195904](https://user-images.githubusercontent.com/17798647/59525565-536cc800-8edf-11e9-9956-202f8ed09e62.jpg)

**Comment by artyorsh** [comment]
omg thanks for the report @deounix 

Looks like this is a custom behavior on Huawei phones because of custom fonts used to style Text elements. We'll fix this soon

Give it a try running on Google devices like Pixel or Nexus. We were able to debug it mostly on these  devices

**Comment by deounix** [comment]
@artyorsh well after spending 2 days 😪 trying to fix this issue I found the hole problem from react-native itself 🤬

Trying to create empty project with react-native >=0.58 u ll see the text and views goes up and down 🤕, now I'm working with react-native@0.57.8 which working good with the old version of ui kitten. not tested yet the newest kitten version.

Please consider this. Thnx.

**Comment by 32penkin** [comment]
Hello @deounix !
After some workaround, we've found an issue with applying custom fonts for Android OS. The font silently reverts back to the system font if "fontStyle" or "fontWeight" styles are applied with a custom "fontFamily". I guess that this's the react-native issue.
You can read more about this in the article: https://medium.com/@lewie9021/custom-fonts-in-react-native-85d814ca084. 
If you will find some interesting solution, welcome to create the PR.

**Comment by artyorsh** [comment]
For now please report in #182 issue. We'll track it progress there

**Comment by ImAbhishekTomar** [comment]
Same issue with iPhone X.

**Comment by artyorsh** [comment]
> Same issue with iPhone X.

@IAmAbhishekTomar We're debugging this app on iPhone X and there is no issue on this device. Any screenshots?

**Comment by IAmAbhishekTomar** [comment]
@artyorah I saw this issue with iOS 12 but I upgrade my phone iOS 12 to 13 beta... I will share some snapshots after downgrading my phone.....

**Comment by ImAbhishekTomar** [comment]
Here is the some snapshot... IOS 13 Beta
![D0D5117A-E2FE-41D0-9215-69CACD709763](https://user-images.githubusercontent.com/6933841/59762842-b76e0280-92ca-11e9-9380-52b4563583cc.png)
![E317B6E9-4FE4-4829-B2A2-1087CDC13BB6](https://user-images.githubusercontent.com/6933841/59762843-b8069900-92ca-11e9-985b-7b1e9f57d120.png)
