### ISSUE TITLE
Question about using this repo as a module

### ISSUE THREAD

**Issue by s0s0s0** [akveo/kittenTricks#184]
Question about using kittenTricks directly as a node_module.

I want to bootstrap an app using this repo (typescript + expo 33 too), and I did `yarn add https://github.com/akveo/kittenTricks.git`. I got the following problem when running expo. `Unable to resolve "@kitten/theme" `.

I feel like the webpack process is having a problem understanding an alias path even tho they are defined in tsconfig in the module level. Does anyone know how to resolve this? Thanks.

**Comment by artyorsh** [comment]
We use this import syntax in a development purpose to quickly review UI Kitten changes in multiple environments.
You need to configure [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) in your project root. [See an example](https://github.com/akveo/kittenTricks/blob/master/babel.config.js) in this project

Btw you can simply replace all `@kitten/theme` and `@kitten/ui` with `react-native-ui-kitten` to get everything working

**Comment by s0s0s0** [comment]
Thanks for quick reply. yah. I am trying to do the replacing. for `@kitten` it is easy but `@src` is hard to fix.
I also tried to update my project root tsconfig with the followings. I get tsc to compile nicely, but I still couldn't get expo to run. react-native still complains about the same thing. I probably missed the setting in babel.config.js.
```
    "baseUrl": "./",
    "paths": {
      "@src/*": ["./node_modules/kittenTricks/src/*"],
      "@kitten/*": ["./node_modules/react-native-ui-kitten/*"]
    },
```


I will try out the babel-plugin-module-resolver setting.

**Comment by s0s0s0** [comment]
Would be super awesome if you could help creating a blank project that import this repo. Pretty sure other people want to see an official example too.

**Comment by s0s0s0** [comment]
I tried reusing all configs from kittenTricks when creating a blank app, but no success.
https://github.com/s0s0s0/kittenTricks/pull/1

**Comment by artyorsh** [comment]
> Pretty sure other people want to see an official example too.

I can not understand why you need this. There is an app published on Google Play and App Store. You also still can cloning repo to launch it locally if needed

See [developer guide](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md#kitten-tricks-environments) to get things working.

**Comment by artyorsh** [comment]
If you still want to launch it locally read more about module resolving. I think you need to replace all imports with an absolute path. But it can also depend on your bundler.
In a few words - you don't need modify tsconfig. This only affects on compiling ts into js
Try get some workarounds with babel as I explained above
