### ISSUE TITLE
Type error ,i am not able to run this example please help me what i need to do, i added all the dependencies

### ISSUE THREAD

**Issue by maheshatti** [akveo/kittenTricks#19]

**Comment by alejandronanez** [comment]
Can you post what errors are you seeing? Also your operative system, etc...?

**Comment by maheshatti** [comment]
![screenshot_20170714-103621](https://user-images.githubusercontent.com/29203167/28199091-85e08718-6880-11e7-96ea-895daaff93a6.png)

**Comment by maheshatti** [comment]
i am using windows 10 pro,64 bit operating system. android version 6.1 marshallow.please help me bro.i need an help
struggling from so many days

**Comment by SashaSkywalker** [comment]
@maheshatti did you make any changes in app routes?

**Comment by malashkevich** [comment]
Hey @maheshatti do you still have a problem? Could you pls describe the issue more detailed?

**Comment by uri3000** [comment]
Not working for me as well

**Comment by malashkevich** [comment]
@uri3000 could you please describe what exactly not work?
Things that help us:
* steps to reproduce
* error log
* reproducible example

**Comment by artyorsh** [comment]
In case it is still actual, we've released v2.0 built with TypeScript. Check this out! :fire:
