### ISSUE TITLE
Half black curve screen on startup - before splash screen

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/kittenTricks#193]
Hi Team,

Can you please look into this issue... because I am using your "kittenTricks" tooling for UI.

Device : Iphone 10 IOS 13 Beta

**Half black curve screen on startup - before splash screen**
https://github.com/facebook/react-native/issues/25405#issue-460912324

**Comment by artyorsh** [comment]
Hi @IAmAbhishekTomar 
Unfortunately, this issue is not related to Kitten Tricks app and we have no idea why this occurs in your app because the source code of Kitten Tricks app works well and during development, we had no similar issues.
Thanks
