### ISSUE TITLE
Crashing on fresh install

### ISSUE THREAD

**Issue by thechosenjuan** [akveo/kittenTricks#196]
### Issue type

**I'm submitting a ...** 
* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
After installing the dependencies with yarn and then doing a ```yarn start```, the app crashes immediately with the stated error in [this picture](https://imgur.com/vkEHVwX). Apparently, there's a component named 'Themes' that is not being exported correctly.

**Expected behavior:**
To be able to see the kittenTricks demo app.

**Steps to reproduce:**
Clone the [kittenTricks repository](https://github.com/akveo/kittenTricks); install dependencies; run the project.

**Comment by tainazao** [comment]
Experiencing exactly the same behavior over here.

**Comment by artyorsh** [comment]
Got it reproduced. Thanks for report

**Comment by duongvanba** [comment]
Version https://github.com/akveo/kittenTricks/commit/50c89c8cedd30cf872620b45c4cc79dd6259ce6e run ok

**Comment by duongvanba** [comment]
Hope this isssue fix soon :(

**Comment by 32penkin** [comment]
Hello @duongvanba and @tainazao ! Thanks for your reports. To be honest I couldn't reproduce this behavior. I've cloned the repo and tried 4 ways:
1. ```yarn && yarn start```
2. ```npm install && npm start```
3. ```rm -rf node_modules && rm -rf package-lock.json &&  yarn && yarn start```
4. ```rm -rf node_modules && rm -rf package-lock.json &&  npm install && npm start```

We will be very grateful if you can share any walkarounds on this.
