### ISSUE TITLE
Help!! Input control icon event

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/kittenTricks#197]
How can i attache event on eye icon in Input control for show/hide password?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by artyorsh** [comment]
Hi @IAmAbhishekTomar. This feature will be available in the next release, please stay tuned

**Comment by ImAbhishekTomar** [comment]
@artyorsh - Can you please provide any out of box solution because this is impacting my development plan... 

Thanks For Support.
