### ISSUE TITLE
How to use the screens in my own project

### ISSUE THREAD

**Issue by Hashedx99** [akveo/kittenTricks#204]
i'm trying to use this kit to implement some UI mainly the article screens , there is no documentation on how to use them whatsoever , all help is appreciated.

**Comment by artyorsh** [comment]
Hi @HSHABx99 
Simply copy and paste the code of a screen you're interested in your project

**Comment by Hashedx99** [comment]
Hi @artyorsh thanks for the fast reply , i tried to do that but it returns an error with invariant violation , and from what i tested it seems to be from container view

**Comment by artyorsh** [comment]
Did you follow [Getting Started Guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/install-ui-kitten)?

**Comment by Hashedx99** [comment]
Yes i did

**Comment by artyorsh** [comment]
Please provide a code you're trying to run

**Comment by thechosenjuan** [comment]
> i'm trying to use this kit to implement some UI mainly the article screens , there is no documentation on how to use them whatsoever , all help is appreciated.

+1

**Comment by thechosenjuan** [comment]
I was also trying the same as @HSHABx99 is trying to do.

@artyorsh ,the Getting Started Guide talks about how to create screens with [UI Kitten](https://akveo.github.io/react-native-ui-kitten/), but if I would like to use the 'Sign In 2' screen on my app, there's no documentation regarding the steps about implementing it.

**Comment by artyorsh** [comment]
@thechosenjuan this App is also built with UI Kitten. To get these screens running in your app with simple copy-paste, you should:
1. [Configure Application Root](https://akveo.github.io/react-native-ui-kitten/docs/guides/install-ui-kitten) as described in the guide.
2. Copy an existing code (Sign In 2 for your purposes) and paste to your app

What else stops you?

**Comment by artyorsh** [comment]
Note that this app is built with TypeScript, so you also need to remove type definitions if you don't use it

**Comment by thechosenjuan** [comment]
> @thechosenjuan this App is also built with UI Kitten. To get these screens running in your app with simple copy-paste, you should:
> 
>     1. [Configure Application Root](https://akveo.github.io/react-native-ui-kitten/docs/guides/install-ui-kitten) as described in the guide.
> 
>     2. Copy an existing code (Sign In 2 for your purposes) and paste to your app
> 
> 
> What else stops you?

@artyorsh the thing that 'stops' me, is that in the code you want me to copy/paste, there are references to other components in this repository. I've tried to do it once; it's at least a 4 component chain that needs to be copy/pasted. It gets confusing.

The original question of @HSHABx99 refers to if there's a way to 'import' the screens the same way that we import the 'theme' from [react-native-ui-kitten](https://github.com/akveo/react-native-ui-kitten/).

**Comment by artyorsh** [comment]
Ah, sorry for the misunderstanding.
So the answer is that you can't. Like any production app, Kitten Tricks has common components that are shared between screens. So you also need to copy and paste them too. There is no automation tool for that.

> we import the 'theme' from react-native-ui-kitten.

UI Kitten exports basic components. It's a UI Kit, not a package of production-ready layouts.

**Comment by thechosenjuan** [comment]
@artyorsh got it.

Thanks for the reply.

**Comment by thechosenjuan** [comment]
@HSHABx99 what I would suggest you to do is use this repository as a base template, and build your app on top of it.
