### ISSUE TITLE
TabView in Sign In 5 example animation fails

### ISSUE THREAD

**Issue by cargallo** [akveo/kittenTricks#205]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The SMS tab's email and password inputs left sides are shown when email tab is selected. And the animation isn't as fluid as the Kitten Tricks published in android play store. I'm testing it in signed apk installed in physical device.

**Expected behavior:**
The screen working as you can see in Kittens Tricks published in android play store

**Steps to reproduce:**
Just clone the repo, install dependencies and expo start

![image](https://user-images.githubusercontent.com/13320290/61070380-f3d1e180-a3e4-11e9-9745-37d1522f0bee.png)

**Comment by artyorsh** [comment]
This is gooing to be an issue of UI Kitten 4.1 I think. Thanks for reporting!

**Comment by tianlinzx** [comment]
I have tried to upgraded to "react-native-ui-kitten": "^4.2.0-beta.2", remains the same.

**Comment by cargallo** [comment]
Unfortunately I gave up using this library and therefore this project. When I understood what it was doing in general, I realized that there was no point in using it and it only adds complexity and dependency of external akveo libraries for things that can be easily achieved in pure code

**Comment by artyorsh** [comment]
@cargallo We're sorry we can't fit your project structure with this template. It was created to simply demonstrate [UI Kitten](https://github.com/akveo/react-native-ui-kitten) features on kind of production examples. During the next releases, we're going to restructure it in a more simple way and update everything :)

In case you found something really complex in using - feel free to [contact us](mailto:contact@akveo.com) for help

Thanks for the feedback :)

**Comment by tianlinzx** [comment]
@artyorsh  Any timeline expectation ?
