### ISSUE TITLE
sketch design version?

### ISSUE THREAD

**Issue by saleem-hadad** [akveo/kittenTricks#228]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

do you provide a sketch design for his amazing work? even if premium?

**Comment by saleem-hadad** [comment]
I found it on sketchupresources
thank you a lot ❤️

**Comment by artyorsh** [comment]
Also, you can take a look at https://github.com/akveo/eva :)
