### ISSUE TITLE
How to use AUTH exemple of UI KITTENTRICKS  ?

### ISSUE THREAD

**Issue by chegmarco1989** [akveo/kittenTricks#231]
Hello.  
I am New in React-Native.  But I wanted to know very exactly HOW TO USE THE EXAMPLES OF UI KITTENTRICKS AVAILABLE IN THE DIRECTORY "/src/components" ???  
For example, if I wanted to use the "AUTH" example (/src/components/auth), how would I proceed ???

Important: If I ask this question, it is because I do not see the part that explains exactly as to use an example in the documentation. 

Please answer me.

**Comment by artyorsh** [comment]
Hi @chegmarco1989 
To get a similar auth interface in your app, you can simply copy and paste components that are used on the screen of your interest (Auth).

Please refer to [this issue](https://github.com/akveo/kittenTricks/issues/204) for details
