### ISSUE TITLE
what is the backend service for feat/state-management branch ?

### ISSUE THREAD

**Issue by tianlinzx** [akveo/kittenTricks#234]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ x] feature request

### Issue description

**Current behavior:**

Notice in .env there is an URL, API_BASE_URL=http://192.168.88.10:8080
**Expected behavior:**

What is the backend service for http://192.168.88.10:8080
**Steps to reproduce:**

git checkout  feat/state-management 
**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, application version **
```
insert information here

```

**Comment by 32penkin** [comment]
Hi @tianlinzx! Thank you for your interest. Unfortunately, this is just a test branch for our internal needs, but in the future, there will be a product similar to the existing one: https://store.akveo.com/collections/all. Something like React-Native-UI-KItten + .Net Core.

**Comment by tianlinzx** [comment]
Wow, the stores looks like a brilliant idea. 
Will support you once it(React-Native-UI-KItten + .Net Core) is launched.

**Comment by 32penkin** [comment]
We will try to keep you posted. Thanks!
