### ISSUE TITLE
Update to Kitten-UI 4.2

### ISSUE THREAD

**Issue by tianlinzx** [akveo/kittenTricks#238]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

As Kitten-UI 4.2 is to be released soon ,shall kittenTrick be updated simultaneously ?
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, application version **
```
insert information here

```

**Comment by artyorsh** [comment]
UI Kitten 4.2 is still a beta fir now, but of course it will be updated as soon as we release 4.2 as a stable version. Thanks
