### ISSUE TITLE
Fresh install fails: "Unable to resolve scheduler/tracing"

### ISSUE THREAD

**Issue by gouaf** [akveo/kittenTricks#240]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
App fails to load with an error that says: << Unable to resolve "scheduler/tracing" from "node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js" >>

**Expected behavior:**
App should load.

**Steps to reproduce:**
git clone  URL
cd DIR
npm install && npm start

**Related code:**

```
Please see screen grab
```

 
<img width="848" alt="Screen Shot 2019-09-18 at 7 16 13 AM" src="https://user-images.githubusercontent.com/8215850/65144282-05d39000-d9e5-11e9-9dc5-348a4fcae4ec.png">

**Comment by gouaf** [comment]
SOLVED! Here are the steps I followed to fix the error:
// from inside project directory //
1. rm -Rvf node_modules
2. rm package-lock.json
3. npm install 
4. npm i scheduler
5. npm audit fix
6. npm start

<img width="388" alt="Screen Shot 2019-09-18 at 12 32 20 PM" src="https://user-images.githubusercontent.com/8215850/65167356-63310680-da10-11e9-8156-a771fe5bf926.png">

**Comment by artyorsh** [comment]
@gouaf I have no idea what is `scheduler` as we don't use it in this app, but congrats with launching :)

**Comment by newhopestar** [comment]
wonderful!!!

**Comment by artyorsh** [comment]
We got this fixed in #241, please wait for the merge 👍
