### ISSUE TITLE
Typo on routes.tsx: DarhboardsNavigationMap

### ISSUE THREAD

**Issue by chinchaun** [akveo/kittenTricks#245]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
DarhboardsNavigationMap

**Expected behavior:**
DashboardsNavigationMap

**Steps to reproduce:**

**Related code:**

**Comment by 32penkin** [comment]
Hi @chinchaun! Thanks for the issue. Will be fixed with https://github.com/akveo/kittenTricks/pull/248
