### ISSUE TITLE
Strange behaviour for Button element in ProfilePhoto component

### ISSUE THREAD

**Issue by pnoyens** [akveo/kittenTricks#246]
Hi there!

So far, everything has worked like a charm using this nice starter template! However, I've stumbled upon a strange bug in the ProfilePhoto component that is included in the src/components/social directory. Here, the edit button element that is defined as a prop when using the <ProfilePhoto /> component, is cloned via React.cloneElement(), overridden with style props from within the component class, and then added to the avatar.

**Expected behaviour:**

Button with onPress functionality that works consistently.

**Actual behaviour:**

The button gets rendered, has the styles included and onPress is triggered when pressed. However, after being pressed a first time, it will act in a different way. I've noticed that long-pressing the button, does not keep the color in dark blue anymore. Somehow the press-functionality gets altered. I'm wondering why that is! The consequence: after a first time press, pressing the button does not trigger onPress anymore.

Any suggestions would be of great help!!

All the best,

Pieter

**Comment by artyorsh** [comment]
@pnoyens thanks for reporting this. I've resolved this by changing styles of Button with simply replacing transform styles. This fix will be available soon

```js
photoButton: {
    top: 82,
    width: 48,
    height: 48,
    borderRadius: 24,
}
```
