### ISSUE TITLE
'react-native-template-react-native-template-ui-kitten-typescript@latest' is not in the npm registry

### ISSUE THREAD

**Issue by ChenZhaobin** [akveo/kittenTricks#250]
when I follow the command " npx react-native init MyApp --template react-native-template-ui-kitten-typescript",
something got wrong like this:

> info Fetching template react-native-template-react-native-template-ui-kitten-typescript...
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-native-template-react-native-template-ui-kitten-typescript - Not found
> npm ERR! 404
> npm ERR! 404  'react-native-template-react-native-template-ui-kitten-typescript@latest' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.

**Comment by ChenZhaobin** [comment]
use command " npx react-native init MyApp --template ui-kitten-typescript" instead ,fixed my problem

**Comment by artyorsh** [comment]
@ChenZhaobin you're on a [legacy React Native CLI](https://github.com/react-native-community/react-native-template-typescript#note-on-the-legacy-cli). Consider upgrading to the latest
