### ISSUE TITLE
Text bug

### ISSUE THREAD

**Issue by Theng** [akveo/kittenTricks#262]
![Screenshot_20200122-145355](https://user-images.githubusercontent.com/12973927/72875822-b224da80-3d27-11ea-8b6c-c6012c4aeb3f.jpg)

Screenshot from OntPlus_3T

**Comment by artyorsh** [comment]
Thanks for reporting. You're running outdated version. Currently, we're working on a major update which is not published yet.
Also, you can find discussion of this issue here: https://github.com/akveo/react-native-ui-kitten/issues/603
