### ISSUE TITLE
get error 'NavigationNativeContainer' has been renamed to 'NavigationContainer 

### ISSUE THREAD

**Issue by ilhamhuda** [akveo/kittenTricks#265]
I've got this error when just starting this project with 'npm start'. how is the solution?

error 'NavigationNativeContainer' has been renamed to 'NavigationContainer'

![image](https://user-images.githubusercontent.com/26187548/73991665-6a38c100-497f-11ea-89d6-3a6aa70f5eaf.png)

**Comment by artyorsh** [comment]
You may need to fix what the error says. See `app.navigator.tsx`
