### ISSUE TITLE
Is Kitten completely free? (because of Backend Bundles)

### ISSUE THREAD

**Issue by whocoded** [akveo/kittenTricks#271]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

Please how free is Kitten React Native components because i'm seeing that you connected payment backed to UI Kitten ?
I dont understand... 

**### here 
[Backend Bundles](https://bit.ly/2IXkl6n) - backend starter kits connected to UI Kitten layouts**

**Comment by artyorsh** [comment]
Backend Bundles is our product which includes screens from Kitten Tricks and some pre-defined business logic and server-side APIs.
So yes, Kitten Tricks is free and that's why it's open-source 👍
