### ISSUE TITLE
Demo app misleading

### ISSUE THREAD

**Issue by somilmathur** [akveo/kittenTricks#278]
Hi I downloaded Kittentricks from play store and absolutely loved everything about it but unfortunately, the demo app is much different from the app on the play store. 

It would be awesome if you could upload the same app on Github as well

**Comment by artyorsh** [comment]
Hi @somilmathur we update store applications on the major releases of the UI Kitten library.
And of course now it may contain some features that are not presented live.
You may see the store code [by switching to a particular release](https://github.com/akveo/kittenTricks/releases).

**Comment by somilmathur** [comment]
Makes sense. Thanks for the prompt response. Love your product, using it in all my new projects. :)
