### ISSUE TITLE
Loading data on screen load

### ISSUE THREAD

**Issue by mkj-git** [akveo/kittenTricks#279]
I have following code, Right now `renderProductItem` is rendered with fixed `products`. I want list to be rendered on screen load. So when screen is loaded it should call an API and render the list based on API response. 

I saw solutions using `state` sopmething like https://github.com/vikrantnegi/react-native-searchable-flatlist/blob/master/src/SearchableList.js but the problem is when i create `constructer` its not getting called on screen load. So i am not sure how to use `state` in my case.

I am unable to figure out how to call an API on screen load and render list once response is available.
   
    export const ProductListScreen = ({ navigation, route }): React.ReactElement => {   
   
      const displayProducts: Product[] = products.filter(product => product.category === route.name);    
      
      const renderProductItem = (info: ListRenderItemInfo<Product>): React.ReactElement => (
        <Card
          style={styles.productItem}
          header={() => renderItemHeader(info)}
          footer={() => renderItemFooter(info)}
          onPress={() => onItemPress(info.index)}>
          <Text category='s1'>
            {info.item.title}
          </Text>
          <Text
            appearance='hint'
            category='c1'>
              {info.item.category}
          </Text>
              <RateBar
                style={styles.rateBar}
                value={4}
              // onValueChange={setRating}
              />
          <CategoryList
            style={styles.categoryList}
            data={["Adventure", "Sport", "Science", "XXX"]}
          />
          <Text>
            The element above represents a flex container (the blue area) with three flex items.
          </Text>
        </Card>
      );
    
      return (
        <List
          contentContainerStyle={styles.productList}
          data={displayProducts.length && displayProducts || products}
          renderItem={renderProductItem}
        />
      );
    };

**Comment by artyorsh** [comment]
duplicates https://github.com/akveo/react-native-ui-kitten/issues/939
