### ISSUE TITLE
Build Fails with message- Failed to notify project evaluation listener 

### ISSUE THREAD

**Issue by hemantbehera** [akveo/kittenTricks#28]
I cloned the app to my local system. Ran Yarn Install successfully. But when I try to deply it to my device, Its throwing error ` A problem occurred starting process 'command 'security'`

**Comment by malashkevich** [comment]
Thanks for reporting we will look into this.

**Comment by ishaq-bhojani** [comment]
@malashkevich  @hemant07rulz  I'm facing same issue, did you guys find any solution?

**Comment by afzali** [comment]
I have problem too :(

**Comment by afzali** [comment]
I can solved the problem:
remove these lines:

android\gradle.properties -> lines 21, 22
RELEASE_STORE_FILE=kittenTricks.jks
RELEASE_KEY_ALIAS=kittenTricks

android\app\build.gradle ->lines 81, 124
def pass = getPassword("alexei","kittenTricks_keystore")
signingConfig signingConfigs.release

**Comment by malashkevich** [comment]
Thanks @afzali we will fix this in next release

**Comment by phantodev** [comment]
@malashkevich i try made this changes above... and this error appears... :-( please u know about?

![image](https://user-images.githubusercontent.com/29681268/31828930-83324d28-b59a-11e7-99b1-7dab63dfda48.png)

**Comment by malashkevich** [comment]
Can you try to remove previous app version from device?

**Comment by phantodev** [comment]
@malashkevich i have in my device the APP from GOOGLE PLAY with EXAMPLES... it is this version that i need remove?

**Comment by malashkevich** [comment]
This two apps has same appId.
As another solution - you can just change appId of app you build.

**Comment by phantodev** [comment]
@malashkevich thanks man... its work... and the last question... so then i gonna study... I did not find in the code where I change to darkTheme. Where i can set this value? There are a CONST or something like that? Thanks very much man!

**Comment by akashdmahali** [comment]
> I can solved the problem:
> remove these lines:
> 
> android\gradle.properties -> lines 21, 22
> RELEASE_STORE_FILE=kittenTricks.jks
> RELEASE_KEY_ALIAS=kittenTricks
> 
> android\app\build.gradle ->lines 81, 124
> def pass = getPassword("alexei","kittenTricks_keystore")
> signingConfig signingConfigs.release

Thanks a lot. @afzali  I too had somewhat similar code in my gradle file, to fetch the password from macOS keychain, but later switched to ubuntu machine and got this error :D
