### ISSUE TITLE
How to build the Project?

### ISSUE THREAD

**Issue by joebetmutia** [akveo/kittenTricks#282]
## 💬 Question
I just grab the latest master branch i was stumble with this error.. any ideas?
## UI Kitten and Eva version
![image](https://user-images.githubusercontent.com/35093942/76774597-166f9200-67df-11ea-930d-2298e2dac8ca.png)

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by artyorsh** [comment]
This code is not from master branch. You will not receive this error if you run the code from master.
