### ISSUE TITLE
Web Version

### ISSUE THREAD

**Issue by rdewolff** [akveo/kittenTricks#286]
## 🚀 Feature Proposal

Is this app working on React Native Web ? If yes, it would be great to make up a CodeSandbox or a web version up and running, accessible for all to play with. If not, it would be great to make it properly render on `react-native-web` 💪 

## Motivation

This would help us discover, use & tests UI Kitten ❤️ 

## Let's get it on

What do you think?

**Comment by artyorsh** [comment]
@rdewolff it is. We even have a netlify badge in a README.md.
https://kitten-tricks.netlify.com/

**Comment by rdewolff** [comment]
Oh nice I did not get that the netlify badge was for the testable web version. Would be great to have a note.

Or even better, add a bigger netlify badge next to the downloadable, testable, App Store and Play Store icons maybe ?

![akveo_kittenTricks__React_Native_starter_kit_with_over_40_screens_and_modern_Light_and_Dark_theme_for_creating_stunning_cross-platform_mobile_applications_](https://user-images.githubusercontent.com/130704/79377214-9d896480-7f5b-11ea-8e0b-a0792c3d4e8f.png)

What do you think?

**Comment by rdewolff** [comment]
Am so used to have the CI and other tests on the top, I don't think it's appropriate to leave it there. Other people must have missed it too.

**Comment by artyorsh** [comment]
@rdewolff can't find an appropriate banner for that 😭

**Comment by rdewolff** [comment]
Maybe that image, cropped with a little additional text will do it :) 

![netlify](https://user-images.githubusercontent.com/130704/79686800-4fb67a00-8243-11ea-8342-aaf638b0c87d.jpg)

**Comment by rdewolff** [comment]
or this

![netlify-2](https://user-images.githubusercontent.com/130704/79686832-7f658200-8243-11ea-9062-8a0e36a8210e.png)
