### ISSUE TITLE
Unexpected end of JSON input while parsing near '...

### ISSUE THREAD

**Issue by dhananjayharel** [akveo/kittenTricks#291]
## 🐛 Bug Report

I am trying to do npm install but getting the following error
Unexpected end of JSON input while parsing near '...

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information
  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD

```bash

```

**Comment by artyorsh** [comment]
Please follow the [Run section](https://github.com/akveo/kittenTricks/blob/master/DEV_DOCS.md#run) of the docs.
