### ISSUE TITLE
Cloned into fresh repo and app fails to start

### ISSUE THREAD

**Issue by exlnt** [akveo/kittenTricks#293]
## 🐛 Bug Report
Unable to run downloaded repo code.

## To Reproduce

- Git clone this repo.
- CD to MyApp folder
- Yarn
- Yarn android

## Expected behavior

The app should start and run in android emulator.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information

  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
  Binaries:
    Node: 12.16.1 - D:\Node.js\node.EXE
    Yarn: 1.22.4 - D:\Yarn\bin\yarn.CMD
    npm: 6.13.4 - D:\Node.js\npm.CMD
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.5 => 0.61.5

```bash

```
[Kitten-Ticks-Error.txt](https://github.com/akveo/kittenTricks/files/4742768/Kitten-Ticks-Error.txt)

**Comment by artyorsh** [comment]
You should start the bundler first, please [see the docs](https://github.com/akveo/kittenTricks/blob/master/DEV_DOCS.md#run).

**Comment by exlnt** [comment]
What do you mean when you say bundler, can you be more specific please?
