### ISSUE TITLE
How to add drawer navigation to tabs navigation

### ISSUE THREAD

**Issue by exlnt** [akveo/kittenTricks#294]
## 💬 Question
I am a fairly new React-Native developer. I still have not picked up TypeScript, so I'm struggling to convert your TS code into plain RN code. I have read all of your get started docs and gone through it step by step. I also read your entire blog post on React-Navigation 5 and UI kitten. I downloaded the code repo for that too. But since it is using TS, I'm finding it difficult to convert it to plain RN(JS) code. 

Here is my **navigation.component.js** file:

`
import React from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {
  BottomNavigation,
  BottomNavigationTab,
  Layout,
  Text,
  Icon,
  Tab,
} from '@ui-kitten/components';
import {HomeScreen} from '../screens/home.component';
import {DetailsScreen} from '../screens/details.component';
import {RequestScreen} from '../screens/request.component';

const HomeIcon = (props) => <Icon {...props} name="home" />;
const DetailIcon = (props) => <Icon {...props} name="list" />;
const RequestIcon = (props) => <Icon {...props} name="clipboard" />;

const {Navigator, Screen} = createBottomTabNavigator();

const BottomTabBar = ({navigation, state}) => (
  <BottomNavigation
    selectedIndex={state.index}
    onSelect={(index) => navigation.navigate(state.routeNames[index])}>
    <BottomNavigationTab title="HOME" icon={HomeIcon} />
    <BottomNavigationTab title="DETAILS" icon={DetailIcon} />
    <BottomNavigationTab title="Request" icon={RequestIcon} />
  </BottomNavigation>
);

const TabNavigator = () => (
  <Navigator tabBar={(props) => <BottomTabBar {...props} />}>
    <Screen name="Home" component={HomeScreen} />
    <Screen name="Details" component={DetailsScreen} />
    <Screen name="Request" component={RequestScreen} />
  </Navigator>
);

export const AppNavigator = () => (
  <NavigationContainer>
    <TabNavigator />
  </NavigationContainer>
);

`

In reading and watching React-Navigation 5 tutorials I should be able to add a drawer navigator by simply creating a drawer navigator and then referencing the Tab navigator in one of the Drawer.Screen entries. 
How can I do the same with UI Kitten components and React-Navigation5 components?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |   5.0.0      |

**Comment by exlnt** [comment]
I created a new component with this code:
[drawer.navigation.component-js.txt](https://github.com/akveo/kittenTricks/files/4742854/drawer.navigation.component-js.txt)

And it leads to this error:
![Screenshot_1591560984](https://user-images.githubusercontent.com/13487337/83979159-25874d00-a8c1-11ea-9756-f6528aa083d7.png)

**Comment by artyorsh** [comment]
@exlnt you're missing the concept of [object destruction](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) usage.
There is no `TNavigator` and `TScreen` in object returned by [createBottomTabNavigator](https://reactnavigation.org/docs/bottom-tab-navigator)
