### ISSUE TITLE
Can't run project with env dev

### ISSUE THREAD

**Issue by arminghm** [akveo/kittenTricks#295]
## 💬 Question
when I run start:dev command I get a lot of these errors

>transform[stderr]: Could not resolve "/Projects/open-sources/react-native-ui-kitten/src/components" in file Projects/open-sources/kittenTricks/src/app/app.component.tsx.

I have react-native-ui-kitten, eva and kittenTricks in a same directory. I did everything said inside dev_docs, but I can't run in dev mode, prod mode is fine.

Am I missing something??
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by artyorsh** [comment]
👋 
The code used to configure paths to both Eva and UI Kitten modules is [here](https://github.com/akveo/kittenTricks/blob/master/env/env.dev.js). Please make sure you have exact [that structure of directories](https://github.com/akveo/kittenTricks/blob/master/DEV_DOCS.md#development-mode) or modify `env.dev.js` with paths to the local modules.

Also, using Yarn is important.
