### ISSUE TITLE
Can we use custom theme component with this application?

### ISSUE THREAD

**Issue by aayushsin** [akveo/kittenTricks#296]
## 💬 Question
Hi, 
I am trying to use the custom theme according to a different brand color in the application. The app theme mappings are really helpful. But according to https://akveo.github.io/react-native-ui-kitten/docs/guides/branding/  , we can use either dark or light theme from the default configurations. 
Is it possible to use both light and dark themes according to the custom theme JSON file with the same mappings with minimal code change? 

Any more documentation or example of the same would highly appreciated! 

## UI Kitten and Eva version
"@eva-design/eva": "^2.0.0",
"@eva-design/material": "^2.0.0",
"@ui-kitten/components": "^5.0.0",
"@ui-kitten/date-fns": "^5.0.0",
"@ui-kitten/eva-icons": "^5.0.0",
"@ui-kitten/moment": "^5.0.0",

**Comment by artyorsh** [comment]
👋 
Switching a theme is documented [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/runtime-theming#runtime-theming)
