### ISSUE TITLE
Argument of type 'null' is not assignable to parameter of type 'MappingContextValue'

### ISSUE THREAD

**Issue by jay-jlm** [akveo/kittenTricks#298]
## 🐛 Bug Report
For these 2 lines in `theme.service.ts`:
```
  static MappingContext = React.createContext<MappingContextValue>(null);
  static ThemeContext = React.createContext<ThemeContextValue>(null);
```

I get the tslint error:
```
Argument of type 'null' is not assignable to parameter of type 'MappingContextValue'
```

## To Reproduce
1. Start a project with React community Typescript template
2. copy `/app`, `/component`, `/assets`, and  `/service` folders to the newly created project

## Expected behavior
No TS errors

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   5.x   |
| @ui-kitten/components   |   5.x      |

## Environment information
React native community template Typescript

**Comment by artyorsh** [comment]
Please follow the [Getting Started](https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#getting-started) guide

**Comment by jay-jlm** [comment]
Can you be more specific?
I did follow the Manual installation guide, the only step I did not run was this one (because I had not yet started the bundle, so I figure I did not need to reset it)
```
npm start -- --reset-cache
```
This guide also does not mention any specific actions involving the need of a custom Typescript configuration.

**Comment by artyorsh** [comment]
Sorry, missed it is a tslint error.
Yes, it probably could be, but it depends on your configuration. We use the [custom one](https://github.com/akveo/kittenTricks/blob/master/tslint.json) in this application as you may notice
