### ISSUE TITLE
When clicking on a chat--always scroll animates down

### ISSUE THREAD

**Issue by bn-l** [akveo/kittenTricks#3]
Why is this? The view should start at the last message.

**Comment by malashkevich** [comment]
Hi @bn-l!
I totally agree with you. But there are some technical problems to implement this now in right way.
To be short -`FlatList` component that we use for chat has property `initialScrollIndex` but this property requires to implement [getItemLayout](http://facebook.github.io/react-native/docs/flatlist.html#getitemlayout) method. 

As soon as chat hasn't equal height it's a bit complex to implement this method. So I decide to put this temporary solution in app. Meanwhile I will try to find a better solution.
