### ISSUE TITLE
How can I use the walkthrough example in my own app?

### ISSUE THREAD

**Issue by ademcan** [akveo/kittenTricks#30]
Hello and thank you for this amazing kitten tricks.
I am working on a new react-native app and would like to implement a similar walkthrough screen as the one you have on the demo app. However, I cannot see any explanation about how to use it even in the Documentation (https://akveo.github.io/react-native-ui-kitten/#/docs/quick-start/getting-started). I installed the package with the npm command but I still didn't manage to get a working walkthrough example. Am I missing something?
I would be grateful for any help.
Thank you.

**Comment by SashaSkywalker** [comment]
Did you run kittenTricks app or run instructions from quick start in documentation?

**Comment by ademcan** [comment]
Hi @SashaSkywalker, thank you for your reply.
I just installed the app on my iPhone. 

What I meant is that there is no explanation on the Documentation part about how to use the Walkthrough example in our own RN app. 
I searched the Documentation for something like RkWalkthrough (I thought it would be named like that...).
I guess you propose me to run it and see directly from the implemented example (?).

**Comment by SashaSkywalker** [comment]
@ademcan, You are right - documentation covers only [react-native-ui-kitten](https://github.com/akveo/react-native-ui-kitten) lib which doesn't include RkWalkthrough.
Anyway you can copy Walkthrough example to your app from kittenTrick:
1. Copy ```Walkthrough``` component from [walkthrough](https://github.com/akveo/kittenTricks/blob/master/app/components/walkthrough.js)
1.  Use it as in [walkthrough screen](https://github.com/akveo/kittenTricks/blob/master/app/screens/walkthroughs/walkthroughScreen.js)
``` html 
<Walkthrough onChanged={(index) => this.changeIndex(index)}>
  <Walkthrough1/>
  <Walkthrough2/>
</Walkthrough>
```

**Comment by ademcan** [comment]
Ah ok I see. I will then try to use it as you metionned (from component).
Thank you very much for your help :)
