### ISSUE TITLE
"Objects are not valid as a React child" Error when using UI Kitten 5.0

### ISSUE THREAD

**Issue by kokhoor** [akveo/kittenTricks#302]
## 💬 Question
When trying to upgrade the UI Kitten library to UI Kitten 5.0, there is an error in the status-bar.component.tsx

The error is at the following line:
`export const StatusBar = styled(StatusBarComponent);`

Error message:
`Error: Objects are not valid as a React child (found: object with keys ($$typeof, render, displayName)). If you meant to render a collection of children, use an array instead.`

What should be the replacement for calling styled?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.0.0       |
| @ui-kitten/components   |  5.0.0       |

**Comment by nvtienanh** [comment]
I think this PR can help you #304

**Comment by kokhoor** [comment]
Great, thanks!
