### ISSUE TITLE
facing problem when run the kitten code for ios with new app. please help, thnx

### ISSUE THREAD

**Issue by KumariShalini** [akveo/kittenTricks#309]
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _RAND_poll in libcrypto.a(rand_unix.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing Recent Messages
Undefined symbol: ___darwin_check_fd_set_overflow

**Comment by malashkevich** [comment]
I guess it's related to the react-native issue https://github.com/facebook/react-native/issues/30231
