### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [akveo/kittenTricks#31]
Do you plan to support RTL layout for RTL languages like Arabic and Persian ?

**Comment by malashkevich** [comment]
Hi @MahdiMajidzadeh.
No, unfortunately we don't have such plans.
Actually you can try to run it in RTL mode. [I think RN should handle 90% of all layout issues.](https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html)
It also always welcomed to make PR's.
