### ISSUE TITLE
Failed to launch the app on IOS simulator (react-native run-ios)

### ISSUE THREAD

**Issue by binhvo-groove** [akveo/kittenTricks#310]
## 🐛 Bug Report

The request to open "com.akveo.kittentricks" failed.
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
	The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for "com.akveo.kittentricks"
	Application info provider (FBSApplicationLibrary) returned nil for "com.akveo.kittentricks"

## To Reproduce

Steps to reproduce the behavior: react-native run-ios

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.4.0    |
| @ui-kitten/components   |    4.4.0     |

## Environment information

```bash
IOS

System:
OS: macOS 10.15.6

Binaries:
Node: 12.18.4
npm: 6.14.6
yarn: 1.22.5
```

**Comment by davidrideout** [comment]
I got the same error (maybe from upgrading Xcode?). For some reason it works fine when I open `KittenTricks.xcworkspace` and build using Xcode.

```
macos 10.15.7
xcode: 12.1

node 12.19.0
npm 6.14.8
yarn 1.22.10
```

**Comment by binhvo-groove** [comment]
When I use terminal to run ios. I got this mess: "info Installing "build/KittenTricks/Build/Products/Debug-iphonesimulator/KittenTricks.app" (**KittenTricks.app**)
While in the project the debug app names **kittentricks.app**
I changed **kittentricks.app** to **KittenTricks.app** then runing ios again. It's worked.
