### ISSUE TITLE
Error: ENOENT "eva/packages/dss"

### ISSUE THREAD

**Issue by valgaze** [akveo/kittenTricks#321]
## 🐛 Bug Report

I'm trying to document the bare-minimum steps to go from zero to a web-browser version of "KittenTricks" with code live-reload. ]

I've encountered some config/build errors. The current blocker is shown below where the application is searching for the ```eva/packages/dss``` path in a directory that is invalid & several "steps" outside the main repo) and I cannot get a web version booted

![image](https://user-images.githubusercontent.com/1396559/118524591-2b052e00-b6f3-11eb-8c86-d9010da2ef5e.png)

## To Reproduce

```sh
git clone https://github.com/akveo/kittenTricks kittentricks_starter
cd kittentricks_starter
cat <<< $(jq '.workspaces = []' package.json) > package.json # see "workspaces" below
npx yarn
npx yarn start:dev
```

## Expected behavior

- See a web version

## Link to runnable example or repository (highly encouraged)

Here's a clunky single-liner (including setting "workspaces" to an empty array):

```sh
git clone https://github.com/akveo/kittenTricks kittentricks_starter && cd kittentricks_starter && cat <<< $(jq '.workspaces = []' package.json) > package.json && npx yarn && npx yarn start:dev
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.1.0"    |
| @ui-kitten/components   |  5.1.0        |

## Environment information

| Service | Version |
| --- | --- |
| Node | v16.1.0 |
| NPM (& NPX) | 7.11.2 |
| Expo | 4.4.7 |

Are any of the versions below poor choices to use with this repo? Are there recommended engines/environments?

```
  System: (macbook)
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
```

Same behavior (except workspace array issue) in node 14.7:

```
  System: (macbook)
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
```

**Comment by valgaze** [comment]
@mishkolesnikov Could you perhaps try the command below on your machine and see if you can get a web version booted from scratch?  If it works, I'd be curious about your ```npx envinfo --preset react-native``` result

```sh
git clone https://github.com/akveo/kittenTricks kittentricks_starter
cd kittentricks_starter
npx yarn
npx yarn start:dev

git clone https://github.com/akveo/kittenTricks kittentricks_starter && cd kittentricks_starter && npx yarn && npx yarn start:dev
```

**Comment by valgaze** [comment]
Update: I "solved" the problem the loader was complaining about (moving a few directories back) because evidently that's how they're configured in this file here: **[https://github.com/akveo/kittenTricks/blob/master/env/env.dev.js](https://github.com/akveo/kittenTricks/blob/master/env/env.dev.js)**

These lookups fail: 

```js
const path = require('path');
module.exports = {
    ENV: 'dev',
    UI_KITTEN_PACKAGES_PATH: path.resolve(__dirname, '../../react-native-ui-kitten/src'),
    EVA_PACKAGES_PATH: path.resolve(__dirname, '../../eva/packages'),
};
```

"Fixed" pathing, no fail:

```js
const path = require('path');

module.exports = {
  ENV: 'dev',
  UI_KITTEN_PACKAGES_PATH: path.resolve(__dirname, '../node_modules/@ui-kitten'),
  EVA_PACKAGES_PATH: path.resolve(__dirname, '../node_modules/@eva-design'),
};

```

**Comment by malashkevich** [comment]
Hello @valgaze, 
Sorry for the confusion. There are [DEV_DOCS](https://github.com/akveo/kittenTricks/blob/master/DEV_DOCS.md) which are actually cover dev mode.

I guess we need to add this into our readme 🤔 
It should be enough to run project quickly
