### ISSUE TITLE
cannot simultaneously extend types 'StyledComponentProps' and 'LayoutProps

### ISSUE THREAD

**Issue by bonzali** [akveo/kittenTricks#324]
S2320: Interface 'SafeAreaLayoutProps' cannot simultaneously extend types 'StyledComponentProps' and 'LayoutProps'.   Named property 'appearance' of types 'StyledComponentProps' and 'LayoutProps' are not identical

`
export interface SafeAreaLayoutProps extends StyledComponentProps, LayoutProps {
    insets?: Inset;
    children?: React.ReactNode;
}`

**Comment by artyorsh** [comment]
You should not extend both. The `LayoutProps` already extends `StyledComponentProps`

**Comment by mikemikhaylov** [comment]
@artyorsh just in case want to highlight that is probably about existing code in this repo https://github.com/akveo/kittenTricks/blob/master/src/components/safe-area-layout.component.tsx
line 14, SafeAreaLayoutProps interface

btw thanks for an amazing ui kit
