### ISSUE TITLE
i just run react-native run-ios , why i change some codes, i enter rr it not any changes?

### ISSUE THREAD

**Issue by buzai** [akveo/kittenTricks#33]
osx 12
node 7

**Comment by malashkevich** [comment]
Hi @buzai.
Did you tried to refresh the app like described [here](http://facebook.github.io/react-native/docs/getting-started.html#modifying-your-app)?

Hope this helps.

**Comment by buzai** [comment]
@malashkevich thank u i konw why not refresh,it is my foo errors
