### ISSUE TITLE
emoji is cutted on top on chat screen

### ISSUE THREAD

**Issue by matheuschagas** [akveo/kittenTricks#35]
![whatsapp image 2017-09-26 at 12 40 17](https://user-images.githubusercontent.com/11858750/30869592-e8cf6652-a2b7-11e7-85a9-9e034f6a8fef.jpeg)
As we can see, the emoji is cutted on top, I think it's because emojis change the line height

**Comment by sergey-kozel** [comment]
Fixed in bcff510d16ce3f8432965b6e6cc0596a8833d4f5
