### ISSUE TITLE
Avatars not found

### ISSUE THREAD

**Issue by mdgiles** [akveo/kittenTricks#39]
<img width="674" alt="capture" src="https://user-images.githubusercontent.com/12366554/32072459-3da7345e-ba58-11e7-84c0-ad5bc3e6a6ce.PNG">

I am trying to get this app running in an Android emulator on Windows 10.  React-native packager reports these errors when navigating to a view that should display avatars, eg Chat. Any ideas on why the avatar images are not found?  I know they are supposed to come from the Realm db and there are no errors populating the initial data.

**Comment by team55** [comment]
same problem in mac os and real android device

**Comment by team55** [comment]
problem in image (or their format). Change image path on other image (photo1.png as example) in populate methods in dataGenerator fixed this problem

**Comment by sergey-kozel** [comment]
No longer relevant after migrating to expo app.
