### ISSUE TITLE
npm install throw error

### ISSUE THREAD

**Issue by adirzoari** [akveo/kittenTricks#40]
I download the project and run 'npm install' I get an error
![errr](https://user-images.githubusercontent.com/20258998/32079743-b0b14848-bab4-11e7-99a7-7531cf4bc2ef.JPG)

**Comment by dimkk** [comment]
npm install --save realm@0.14.3

fixed for me

**Comment by sergey-kozel** [comment]
No longer relevant after migrating to the expo in 69662cfd6df3bcb765ae5cdd437c0aac293a67a4. Realm is not used anymore.
