### ISSUE TITLE
RkSwitch's onValueChange is not working... :(

### ISSUE THREAD

**Issue by jbaek7023** [akveo/kittenTricks#42]
<RkSwitch
              style={styles.switch}
              value={this.state.inWardrobe}
              name="Push"
              onValueChange={(inWardrobe) => {console.log('helloworld')}}/>

This can't print `helloworld`. 

But when I click the switch, the value seems changing automatically. (I didn't do setState here)

**Comment by sergey-kozel** [comment]
Hi @jbaek7023,

RkSwith is not working properly as component now in Android (do have troubles only with Android, right?). We plan to fix it and add to the react-native-ui-kitten library soon.

You can track status of this task via https://github.com/akveo/react-native-ui-kitten/issues/72
