### ISSUE TITLE
Calling a function in RkModalImg

### ISSUE THREAD

**Issue by harshrajk** [akveo/kittenTricks#43]
Is there any way to call a custom function from RkModalImg footer ?

**Comment by sergey-kozel** [comment]
Hi @harshrajk,

Yes, it is possible and described here https://akveo.github.io/react-native-ui-kitten/#/docs/ui-components/rkmodalimg. The only difference is that you need to use 'renderFooter' instead of 'renderHeader':

```
_renderFooter(options){
  return (
    <View>
      <RkButton onPress={(x) => Alert.alert('I Like it!')}>Custom Header</RkButton>
    </View>
   );
}

 //...
 <RkModalImg source={require('../img/river.jpeg')}  renderFooter={this._renderFooter}/>
```

**Comment by harshrajk** [comment]
Thank you for the quick response @sergey-kozel.I am trying to get access of pageNumber or image link from options and using it in another function. E.g. this.share(imagedata) in onPress but getting 'not a function error'.Great library bdw.Loved it !

**Comment by sergey-kozel** [comment]
Can you provide some example of your code? Maybe you do something wrong. RkModalImage just call your renderFooter with parameter {closeImage, pageNumber, totalPages} when it renders its content in order to you can specify your custom footer content. If you create there a button with onPress handler where you use pageNumber for example then I do not see any reasons why it should't work.

**Comment by harshrajk** [comment]
Again, thank you for your response.

` <ScrollView>
            <View
              style={[
                styles.product_bottom_cat_section,
                { justifyContent: "center", paddingTop: 8 }
              ]}>
              {this.arr.map((image, index) => {
                return (
                  <RkModalImg
                    key={index}
                    style={styles.usergallery_bottom_cat_3}
                    modalImgStyle={{
                      flex: 1,
                      resizeMode: "contain",
                      justifyContent: "center"
                    }}
                    renderHeader={this._renderHeader}
                    renderFooter={this._renderFooter}
                    source={this.arr}
                    index={index}
                  />
                );
              })}
            </View>
          </ScrollView>

**footer function***
  _renderFooter(options) {
    return (
      <TouchableOpacity
        style={{ marginRight: 10 }}
        onPress={() => this.share(options.pageNumber)}>
        <Text
          style={{
            fontSize: 12,
            marginRight: 5,
            borderRadius: 15,
            fontWeight: "600",
            color: "#fff",
            padding: 5
          }}>
          {" "}<Icon name="share" size={15} color="#fff" /> Share{" "}
        </Text>
      </TouchableOpacity>
    );
  }


**share**

  share(no) {
    console.log(no);
  } 
`


I'd also tried this._renderFooter(image) but failed to get it inside render function

**Comment by sergey-kozel** [comment]
Don't you get any results in console? It's strange. Did you try to debug?

**Comment by harshrajk** [comment]
No I get error saying **_this2.share** undefined.

**Comment by sergey-kozel** [comment]
You bound your share function with this `() => this.share(options.pageNumber)` but you need also bind _renderFooter with `renderFooter={this._renderFooter.bind(this)}` or in any other way. You just lost your context.

**Comment by harshrajk** [comment]
Oh ! I think that's it.Thanks @sergey-kozel
