### ISSUE TITLE
I can't reject expo

### ISSUE THREAD

**Issue by locxm93** [akveo/kittenTricks#47]
I want convert project from **_project expo_** to _**react native init**_. I run:
_npm run eject_ 
but not success.
Please review it.
Thank.
Loc

**Comment by sergey-kozel** [comment]
Hello @locxm93,

Could you please provide more detailed information? On what step did you stop? What messages do you receive?

**Comment by locxm93** [comment]
Hello sergey-kozel,
When I run _npm run eject_ then It show is:
![image](https://user-images.githubusercontent.com/25600386/35131360-43e64f7a-fcf8-11e7-90a1-7ccf94f058e8.png)

After I run _react-native run-ios_ :
![image](https://user-images.githubusercontent.com/25600386/35131378-659edc86-fcf8-11e7-9d7c-39cf1c6f18a2.png)
I rename folther from **temp-android-directory** to **android** and run _react-native run-android_
![image](https://user-images.githubusercontent.com/25600386/35131481-f7325d26-fcf8-11e7-8bf7-87bd228f51cc.png)
I use nodejs 9.4
Thank.
Loc

**Comment by sasanazizi** [comment]
@malashkevich was this issue solved ?! why you closed it ?!

**Comment by malashkevich** [comment]
Hello @sasanazizi.
Yes, it was solved by commit 9f708ef.

**Comment by sasanazizi** [comment]
@malashkevich Tnx.

**Comment by sasanazizi** [comment]
@malashkevich hey!
after i reject expo , i have an error ! 
when i run "npm run android" shows an  error in emulator that is "Unable to resolve module `./App` from `mobile-app/kittenTricks/index.js`"

How can i solve it ?!
Tnx
