### ISSUE TITLE
How to pass custom parameters to Screen by routes?

### ISSUE THREAD

**Issue by fukuball** [akveo/kittenTricks#5]
Just saw this demo, want to know how to pass custom parameters to Screen View by routes(so we can change view with remote data)?

**Comment by malashkevich** [comment]
Hi @fukuball.
In our project we are using [react-navigation](https://reactnavigation.org/docs/intro/). It has built-in support for passing parameters.

**Comment by fukuball** [comment]
@malashkevich Cool~
