### ISSUE TITLE
TabNavigator

### ISSUE THREAD

**Issue by esdonmez** [akveo/kittenTricks#51]
I add tabbar for navigation in my project but I have got some trouble while I try to add theme on it. Because the routes.js page is the first thing that compiled, I cannot get the current theme. I tried to create a component but then the tabbar disappeared or its style disappeared completely.

`<Scene 
                            tabs
                            key="tabbar"
                            showLabel={false}
                            lazy
                            hideNavBar
                            tabBarStyle={styles.tabBarStyle}
                            headerMode="screen"
                        >
                            <Stack
                                key="tab1"
                                title="Events"
                                tabBarLabel="Events"
                                icon={TabIcon}
                                onEnter={
                                    console.log("esd")
                                }
                                initial
                             >....</Stack>
                             .....
                         </Scene>`

**Comment by web75018** [comment]
hI esdonmez.
did you fixed this issue?
i'm trying the same thing.

**Comment by esdonmez** [comment]
Unfortunately I couldn't implement theme on my tabbar but maybe you can figure it out looking this demo project.
https://github.com/akveo/react-native-ui-kitten-demo-app

**Comment by web75018** [comment]
Thanks for help!
