### ISSUE TITLE
Custom Menu but loading other routes

### ISSUE THREAD

**Issue by bnbon** [akveo/kittenTricks#52]
Hello,

How to create a system where I have a series of routes loaded in my App, and then I want a separate list of routes which are in the sideMenu?

I tried splitting the routes into the two exports, and rather than doing a clone of mainRoutes into Menu, I had fewer routes in the menuRoutes so I could pare it back.

It's just not very clear how to avoid the scenario of routes only working when they are in the Menu system... or should I rip out the menu system and build another from scratch? (Which seems a waste as I want to use DrawerNavigator).

**Comment by bnbon** [comment]
Anyone? :)

**Comment by malashkevich** [comment]
Hello @bonbonio.
Tbh, I'm not sure I understand what difficulties do you have.
So you want to have separate routes for DrawerNavigation and some another navigation?

**Comment by bnbon** [comment]
All the main routes are loaded into the menu.

What I want is to be able to define the routes I want in the menu, but as I am only using 1 level of menu, there will be many routes in the App I will create and wish to navigate to, but I don't want it to be a requirement for them to be in the menu.

So maybe a way to declare all routes, and then a way to declare which routes to load into the DrawerNavigation.

Make sense?

**Comment by malashkevich** [comment]
Ok, so you want to type routes: Routes that available from sidemenu and routes that will be available as steps from root navigator, right? 
If so, why not create this structure:

```
const DrawerExample = DrawerNavigator({
  Inbox: {
    screen: StackNavigator({
      Inbox: {
        screen: InboxScreen
      },
      Email: {
        screen: EmailScreen
      },
    });,
  },
  Drafts: {
    screen: StackNavigator({
      Drafts: {
        screen: DraftsScreen
      },
      Email: {
        screen: EmailScreen
      },
    });
  },
}, {...});
```
Took this exmaple from [here](https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/Drawer.js).

**Comment by bnbon** [comment]
So how would that work with the routesBuilder.js used in this example, I'd just declare a new stack under the DrawerNavigator?

A fiddle would help, but I will see what I can do - I am still *very* new to React/React-Native so I appreciate your help.

**Comment by malashkevich** [comment]
routeBuilder.js just create structure above automatically. I'm pretty sure you shouldn't do it in your project. As long as you are new in react-native and react-navigation - you better start from simple navigation structures.
So yes, you can create new Stack under Drawer and it's very common use case.

There is [quite a good series of articles](https://medium.com/async-la/react-navigation-are-you-the-one-8cf945a4a462) of @computerjazz. Check them out first. Also most it's better to ask questions regarding react-navigation in theirs [repo](https://github.com/react-community/react-navigation).
