### ISSUE TITLE
Invalid prop types: props.style key fontSize supplied to view

### ISSUE THREAD

**Issue by loic-lopez** [akveo/kittenTricks#53]
### Issue type

**I'm submitting a**

* [x] bug report

### Issue description

**Current behavior:**
```
Invalid prop types: props.style key fontSize supplied to view
```

**Steps to reproduce:**
Go to login V1 in Auth section.

### Other information:

**IOS, Iphone6, latest version of master branch**

See the logs bellow : 

<img src="https://user-images.githubusercontent.com/17724398/35989945-cc82da0a-0d02-11e8-953c-105009de55ed.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/17724398/35989952-cff908e4-0d02-11e8-8062-41810d950840.png" width="200" height="400" />

**Comment by malashkevich** [comment]
Hello @loic-lopez.
Thanks for reporting. This is actually a duplicate of #50.
We plan to fix it in future versions.
