### ISSUE TITLE
Android Back Button is not working

### ISSUE THREAD

**Issue by db-sc** [akveo/kittenTricks#57]
I am using kittenTricks but I am facing one issue. In my app `BackHandler` is not working. It is working with Debug Js Remotely only but not in production and development mode. But in your kitten tricks app without BackHandler it is managing the android back button press. So can you please help me out in this. 
 I tried this but it works in Debug Js mode. 

    componentDidMount() {
        BackHandler.addEventListener('hardwareBackPress', this.onBackPress.bind(this));
    }

    componentWillUnmount() {
        BackHandler.removeEventListener('hardwareBackPress', this.onBackPress.bind(this));
    }

    onBackPress = () => {
        if (this.props.navigation.state.routeName === 'GridV1') {
            BackHandler.exitApp();
            return true;
        } else {
            return false;
        }
    };
So anything other than this if you're using then  @akveo-bot @akveo-private please solve my problem it's quite urgent.

**Comment by artyorsh** [comment]
In case it is still actual, we've released v2.0. Check this out! :fire:
