### ISSUE TITLE
Not working after ejecting from expo to native 

### ISSUE THREAD

**Issue by msameerbm** [akveo/kittenTricks#58]
I need this project as react native init app structure, so i ejecting using npm run eject, after that its not working. Please make this native project of kittenTricks.

**Comment by malashkevich** [comment]
Hi @sameercodes.
What erros do you have?

**Comment by msameerbm** [comment]
@malashkevich Its showing "Require Expo SDK" , please can i have this same project with native? project structure with android and ios folder?

**Comment by ghost** [comment]
@sameercodes same thing here. Did you find a workaround?

**Comment by msameerbm** [comment]
@fedecryto No.

**Comment by mmirzaeyan** [comment]
i got this error : 
`error: bundling failed: Error: Unable to resolve module `scheduler/tracing` from `/Users//kittenTricks-master/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js`: Module `scheduler/tracing` does not exist in the Haste module map`

**Comment by artyorsh** [comment]
In case it is still actual, we've released v2.0 built on top of Expo SDK 33. Check this out! :fire:
