### ISSUE TITLE
how to remove Expo

### ISSUE THREAD

**Issue by wahello** [akveo/kittenTricks#59]
### how to remove Expo

Expo is extremely slow.

**Comment by esdonmez** [comment]
I, personally, opened a new project and move all the project files from kittenTricks to the new project, also installed all the npm packages except expo. The only thing that depends on the expo was Gradient Button which I don't use in my project, but if you want to use it, you can easily find a replacement for it.

**Comment by famoustunde** [comment]
Hello @esdonmez Please how did you replaced the GradientButton from expo ?

**Comment by msouidi309** [comment]
Hi @esdonmez, just delete "expo" from "package.json" before doing "npm install". I think it's easier =)

**Comment by esdonmez** [comment]
@famoustunde I just used a normal button but you can use [react-native-linear-gradient](https://github.com/react-native-community/react-native-linear-gradient) package.

**Comment by famoustunde** [comment]
Thanks

**Comment by prasadpilla** [comment]
Hey @esdonmez, I'm having a hard time getting this to work when move over the project files to a new react native vanilla project. 

May be because something different in the react native app i just generated?

Can you please let me know if you had to change any versions?

**Comment by prasadpilla** [comment]
Got it working by re-doing it carefully. 

1. Inti a new app
2. Copy over screens and components, package.json
3. Remove Expo dep
4. Remove Gradientbutton refs

**Comment by esdonmez** [comment]
Hi @prasadpilla. Sorry for late reply. I'm glad you solved your problem. 
@msouidi309 It would be easier but I ran project with expo first, after a while I wanted to remove it from the project but I'd some problems with it. Finally, I decided to create a clean project. :)

**Comment by ElangoPrince** [comment]
Hi @esdonmez, when i remove expo file from package.json, having lot of errors. let me know anyone which file's are removed from the expo.

**Comment by esdonmez** [comment]
@ElangoPrince I'm not quite sure about all the files I removed because it was almost 1 year ago. As I remember, I removed 
- "expo": "28.0.0",
- "expo-analytics": "1.0.6"

from package.json.
I also removed "Gradient Button" from the components of react-native-ui-kitten. It may work with it but as I said, I don't really remember.
Maybe you can send me the errors, so I can tell what causes the problem.

**Comment by jafar690** [comment]
@esdonmez i copied all the files over to a new project and removed expo dependencies, but i get this error

`Invariant Violation: The navigation prop is missing for this navigator. In 
react-navigation 3 you must set up your app container directly. More info: 
https://reactnavigation.org/docs/en/app-containers.html`

any solutions?

**Comment by famoustunde** [comment]
@jafar690 Hello, you can follow this thread to solve that issue. (Link below)
From my understanding, this is simply caused by the  various changes in React Navigation V 3 expecially the explicit app container required for the root navigator. I hope this helps
[https://stackoverflow.com/questions/53367195/invariant-violation-the-navigation-prop-is-missing-for-this-navigator](url)

**Comment by jafar690** [comment]
@famoustunde thanks, also do you know how i can use the Expo Font package in a react init application?

**Comment by famoustunde** [comment]
> @famoustunde thanks, also do you know how i can use the Expo Font package in a react init application?

@jafar690 
To be honest with I have not been able to do this by myself, but I have not tried in long time. Maybe this information could help you. [https://stackoverflow.com/questions/44748213/convert-expo-project-to-original-react-native-project?rq=1](url)
I will give it a try later on and feedback on how to use the Expo font package.

**Comment by artyorsh** [comment]
In case it is still actual, we've released v2.0 built on top of Expo SDK 33. Check this out! :fire:
