### ISSUE TITLE
Sometimes touches are not detected

### ISSUE THREAD

**Issue by longsangstan** [akveo/kittenTricks#6]
First of all really awesome project!

However I have found that sometimes my touches are not recognized, so I have to press twice.

Does anyone else has the same issue? Is it a react-native issue (rather than this library)?

My device is iPhone 7. Thanks.

**Comment by elupanov** [comment]
Thank you @longsangstan !
Could you tell please on what items and on what views you have to press twice?

**Comment by longsangstan** [comment]
@elupanov basically every touchable item... but most notably the sidebar icon in top left corner and the items in the sidebar

**Comment by malashkevich** [comment]
@longsangstan This probably can be due relatively small size of touchable area of this button.
We will look into this.
Thanks for sharing!

**Comment by longsangstan** [comment]
UPDATE:
Actually I think it is more of a react-native issue. I have the same issue with other RN apps as well.
It usually happens when I perform the touches too quickly. I am not 100% sure though.
Thanks anyway!
