### ISSUE TITLE
how to use this project

### ISSUE THREAD

**Issue by wushunqing** [akveo/kittenTricks#60]
I download this project, and i'm Execute a command ‘npm install’  and 'react-native-scripts start'.
a app was installed.
![image](https://user-images.githubusercontent.com/20431475/38179847-3b614b16-365a-11e8-9b8d-b6a3cca2c714.png)

It's name Expo.but i don't nedd this app. I'm just want to kittenTricks.
![image](https://user-images.githubusercontent.com/20431475/38179861-5f9d84fe-365a-11e8-9586-00bb5fa7125c.png)

how can i do ,please help me,Thanks!

**Comment by artyorsh** [comment]
Hi @wushunqing,
Sorry for late reply.

First of all Expo is a tool for developers to help them build and deliver RN apps to devices.
For personal use you even don't need this, if app is published somewhere outside Expo, e.g [AppStore](https://itunes.apple.com/us/app/kitten-tricks/id1246143230?mt=8).

If you want to build and debug it using your IDE you still need using Expo.
