### ISSUE TITLE
App crashes in react-navigation v2

### ISSUE THREAD

**Issue by kashsbd** [akveo/kittenTricks#62]
Hello Guys,  awesome library .
But it crashes in react-navigation v2
Could you please update this demo app ?
Thanks.

**Comment by PatNeedham** [comment]
@B4UGUYS when exactly does it crash for you? I was trying out the Android application from the Play Store earlier (before looking into the code), and noticed this sequence of screen transitions / button clicks causes a crash:
Grid Menu -> Articles -> Blogposts -> click any post -> click on profile / avatar on right hand side.
After doing that, sometimes it completely crashes while sometimes it just resets the app and starts from the splash screen again.

**Comment by kashsbd** [comment]
I face the same problem plus when I start the project from source it crashes in splash screen.How about you ?Did you try from source ?

**Comment by artyorsh** [comment]
Hi guys,
If you need solution asap, you can check my fork of this repo.
These changes will be available in future release, I hope ;)
