### ISSUE TITLE
unable to load app in simulator

### ISSUE THREAD

**Issue by ps0305** [akveo/kittenTricks#63]
### simulator related

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ x] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
/bin/sh: react-native-scripts: command not found
error Command failed with exit code 127.
```

### Other information:

**OS, device, application version **
```
Mac mini(A1347),Xcode

```

**Comment by artyorsh** [comment]
Hi @ps0305,
Do you have node modules installed after cloning kittenTricks repo?

**Comment by ps0305** [comment]
Hi,issue resolved, having some problem due to yarn ,switched to npm.
it's working fine now!
