### ISSUE TITLE
how to use react-native run-ios on the MAC

### ISSUE THREAD

**Issue by hedywstylz** [akveo/kittenTricks#68]
I am a novice rn, how can i use this project's example on the mac, like other projects, using react-native run-ios debugging effect. this project has no IOS and Android project files, how to use react-native run-ios on the MAC debugging example? thank you.

**Comment by artyorsh** [comment]
Hi @hedywstylz,
You simply clone this repo, and using command-line inside project root run:
* npm i
* npm run start
* react-native run-ios

**Comment by hedywstylz** [comment]
I did npm i I and npm run start according to your steps, and that's the interface，

Or enter this address in the Expo app's search bar:
  exp://10.213.215.108:19000
Your phone will need to be on the same local network as this computer.
For links to install the Expo app, please visit https://expo.io.
Logs from serving your app will appear here. Press Ctrl+C at any time to stop.
 › Press a to open Android device or emulator.
 › Press q to display QR code.
 › Press r to restart packager, or R to restart packager and clear cache.
 › Press d to toggle development mode. (current mode: development)

So now i need to use another console to execute react-native run-ios？

**Comment by hedywstylz** [comment]
it don‘t have the ios project,like .xcodeproj,how to solve this problem.thank you

**Comment by hedywstylz** [comment]
@artyorsh it don‘t have the ios project,like .xcodeproj,how to solve this problem.thank you
I did npm i I and npm run start according to your steps, and that's the interface，

Or enter this address in the Expo app's search bar:
exp://10.213.215.108:19000
Your phone will need to be on the same local network as this computer.
For links to install the Expo app, please visit https://expo.io.
Logs from serving your app will appear here. Press Ctrl+C at any time to stop.
› Press a to open Android device or emulator.
› Press q to display QR code.
› Press r to restart packager, or R to restart packager and clear cache.
› Press d to toggle development mode. (current mode: development)

So now i need to use another console to execute react-native run-ios？

**Comment by artyorsh** [comment]
@hedywstylz 
On step when you started packager and got the output you described you can:
* open separate terminal process and run react-native run-ios
**or**
* simply follow output instructions and press i

If you want to understand why this project doesn't have android and ios subdirs, you can read the [expo](https://expo.io) docs
