### ISSUE TITLE
Dashboard shows red screen

### ISSUE THREAD

**Issue by tmaly1980** [akveo/kittenTricks#7]
Every other screen works fine, except the dashboard. It's a fresh install, I ran "yarn install" then "react-native run-ios".
![screen shot 2017-06-30 at 5 35 07 am](https://user-images.githubusercontent.com/7697371/27735825-4d223cb2-5d56-11e7-82f8-6be47ceff265.png)

**Comment by jkomyno** [comment]
That happens on Android too

**Comment by SashaSkywalker** [comment]
Thank you for submitting issue, fixed via 37a78236492d3d3cd55da8476d0c65a062764752
