### ISSUE TITLE
Realm ( false advertising ) ?

### ISSUE THREAD

**Issue by sahanatroam** [akveo/kittenTricks#70]
Hi do you think having `realm`, on the README.md is misguiding people looking for project boilerplate with realm ?

**Comment by artyorsh** [comment]
Hi @sahanatroam ,

Thanks for report. The reason of your issue is that we just forgot update readme file after some changes. [Take a look.](https://github.com/akveo/kittenTricks/commit/1b0f4f0553f4facc489832686fccf2f8c0a367cb)

**Comment by sahanatroam** [comment]
@artyorsh thanks,
amazing work overall on this project tho :)
