### ISSUE TITLE
undefined is not an object ('evaluating 'getPrototypeOf(sourceCompontent)')

### ISSUE THREAD

**Issue by hackersdoit** [akveo/kittenTricks#72]
Why I'm seeing this?
when I bulid the IOS app (app.js) it gives me this error undefined is not an object ('evaluating 'getPrototypeOf(sourceCompontent)')
<img width="1440" alt="screen shot 2018-09-19 at 1 28 36 pm" src="https://user-images.githubusercontent.com/25680928/45751027-5cab5b80-bc11-11e8-82c6-8acf31da6cba.png">

### Other information:

**OS, device, application version **
OS: macOS, iPhone 7 simulator

**Comment by axd** [comment]
It seems that you are not giving a real source target to Hoist Non React function, also not sure if that component is supported for react-native. Anyway, just check if the target source is imported in your js file.

**Comment by jafar690** [comment]
@axd i am also getting this error, how do i solve?

**Comment by artyorsh** [comment]
@jafar690 
In most cases it means you have a problem which can be solved with @axd 's solution
>  just check if the source component is imported in your js file.
