### ISSUE TITLE
FontIcons: how to create a new one

### ISSUE THREAD

**Issue by numediaweb** [akveo/kittenTricks#73]
I couldn't find any information about FontIcons mentioned in the [icons.js](https://github.com/akveo/kittenTricks/blob/master/app/assets/icons.js). I think this is not related to Fontawesom: Is this a proprietary font or is it included via an external package?

If you check the icons.js file it shows only squares but renders well on the emulator.

**Comment by esdonmez** [comment]
Hi,

FontIcons is related with IcoMoon font. If you paste any icon from that font, you can use it in your project. 

The usage is: (..\app\screens\social\profile2.js)
`<RkText rkType='moon large primary'>{FontIcons.profile}</RkText>`

**Comment by nafiln** [comment]
@esdonmez could you please give example of changing the icon. Because its not clear

**Comment by gatoasang94** [comment]
Hi nafiln,
The steps are as follows:
1. Download font bundle from https://icomoon.io/#icons-icomoon
2. Open file Reference.html under Font
3. Copy the icon you want (show as a square)
