### ISSUE TITLE
Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 7.0.0, 8.0.0, 9.0.0

### ISSUE THREAD

**Issue by DilipCoder** [akveo/kittenTricks#74]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request
### Issue description

**Current behavior:**

 Starting packager...
***ERROR STARTING PACKAGER***

Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 7.0.0, 8.0.0, 9.0.0

**Expected behavior:**
App should compiled without the error as app.json and package.json file have same "28.0.0" version number.

**Steps to reproduce:**
I have downloaded the repository and extract the zip file.
run ```yarn install or npm install```
run ```npm start```

### Other information:

**OS, device, application version **
```
platform : win32 
arch : x64 
os: windows 10
Node: 10.14.1
npm: 6.4.1
yarn: 1.12.3
expo-cli: 2.6.0
```

**Comment by artyorsh** [comment]
Hi @DilipCoder 
Thanks for report.
With the same config but running on a mac I'm unable to reproduce it

**Comment by 32penkin** [comment]
Hello @DilipCoder. Just tried to reproduce the issue on my local env. and in fact the same settings as yours. Unfortunately it was not possible to provoke it.
Please, keep us posted if you find any other information about this.
