### ISSUE TITLE
Upgrading this project to expo 31 causes an error

### ISSUE THREAD

**Issue by Oakyden** [akveo/kittenTricks#79]
This error appears if you upgrade to expo 31.  - https://github.com/react-native-community/react-native-svg/issues/591 

I believe this is due to expo including react-native-svg as a dependency. However, victory-chart also directly includes it as a dependency.

From what i can see the only solution is to keep expo at a version before this was included or to remove anything to do with react-native-svg from the project such as victory charts.

Any other ideas?

**Comment by astw** [comment]
> This error appears if you upgrade to expo 31. - [react-native-community/react-native-svg#591](https://github.com/react-native-community/react-native-svg/issues/591)
> 
> I believe this is due to expo including react-native-svg as a dependency. However, victory-chart also directly includes it as a dependency.
> 
> From what i can see the only solution is to keep expo at a version before this was included or to remove anything to do with react-native-svg from the project such as victory charts.
> 
> Any other ideas?

same error here.

**Comment by artyorsh** [comment]
In case it is still actual, we've released v2.0, which supports SDK 33. Check this out :fire:
