### ISSUE TITLE
Can I use it with expo ?

### ISSUE THREAD

**Issue by xcarpentier** [akveo/kittenTricks#8]

**Comment by elupanov** [comment]
Hi @xcarpentier !
Here is a link to expo https://expo.io/@community/kitten-tricks

**Comment by lukevenediger** [comment]
Hi @elupanov, I'm struggling to see how kitten tricks now supports expo. The app.json file doesn't have an "expo" section and the Expo package isn't included in the package.json file. Am I missing something? Thanks!

edit: oops, mentioned the wrong guy!

**Comment by akmittal** [comment]
Better question would be, How to build the app and run into expo. I don't think it stiff supports expo.

**Comment by malashkevich** [comment]
Hello. Sorry for delay. Right now app doesn't support expo because of some native libraries that do not work with expo. We are using `realm.io` as data storage. We will think about migrate our project to expo.

**Comment by lukevenediger** [comment]
Ack thanks @malashkevich!

**Comment by ericklarac** [comment]
@lukevenediger how can I run the project without expo?

Wish you could help me.

**Comment by sergey-kozel** [comment]
Hello @ericklarac,

Can I clarify what do you mean by "run the project without expo"?

If you want to run it from your local machine you can do it through `yarn` and then `yarn start`. It will work in the same way as earlier except it will be executed by expo app. You can debug it, inspect etc.

If you want to turn the app from expo to regular react-native app you can do ejecting or detaching. But before you do that read the docs and make sure that you really need it. Expo offers rich API and covers a lot of usual cases.

https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md
https://docs.expo.io/versions/latest/guides/detach.html

**Comment by ericklarac** [comment]
@sergey-kozel thanks, actually I already read it and it's running like a brand new project.

**Comment by asallem** [comment]
This project uses Expo SDK v18.0.0. If you want to open this project, the author will need to update the project's SDK version.
