### ISSUE TITLE
Kitten Tricks installed after restoring iOS Device

### ISSUE THREAD

**Issue by zanesc** [akveo/kittenTricks#80]
So the strangest thing just happened to me. I restored my iPhone X to iOS 12.1.3 through iTunes on my Mac, allowing Apple to fetch the IPSW from it's own servers. I did not restore from any backup and I set the phone up as a new phone.

I went through the standard device setup process. Then, to my absolute surprise and without opening any apps, I see that "Kitten Tricks" is already installed onto my completely wiped device.

I've never heard of Kitten Tricks before this moment. How did this happen? To my knowledge this is not possible.

**Comment by artyorsh** [comment]
That's really interesting, @zanesc 
Any steps to reproduce? 😄
