### ISSUE TITLE
Default Theme Is Not Changing

### ISSUE THREAD

**Issue by saadikhurshid** [akveo/kittenTricks#82]
I am trying to set Dark Theme as default theme but nothing happens as app loaded with default white them event i tried To setRk theme in app.js

**Comment by artyorsh** [comment]
Hi @saadikhurshid 
Sorry for late reply. Could you please provide the code you used while trying to achieve this?

**Comment by saadikhurshid** [comment]
Thank you for reply
So error was from my end. I have fixed the issue but in logins screen kindly add scroll view as in android mobile when we tap on input filed it wont go up and hide behind kepad
