### ISSUE TITLE
Best way to rename the project?

### ISSUE THREAD

**Issue by longsangstan** [akveo/kittenTricks#9]
Hi I am using kittenTricks as a starter kit for my new project.

I just wonder do you have a recommended way to rename the project? I have tried the "react-native-rename" npm but not all files are renamed. Of course I can try to rename them manually but I just don't want to miss anything or mess anything up.

Thanks.

**Comment by Mirodil** [comment]
+1

**Comment by gailingmic** [comment]
while its a good idea to peek into some already existing code it wont help you much with understanding react / react native first. I would strongly suggest that you start with something small first with the help of a book / video tutorial. :)

**Comment by longsangstan** [comment]
@gailingmic I am not using kittenTricks as an absolute beginner, I have already built several react/react-native apps.

I use kittenTricks as it has nearly all the building blocks I needed for my next app (great work by the authors!).

Thanks for your suggestion anyway :)

**Comment by junedomingo** [comment]
@longsangstan renaming this project with [react-native-rename](https://github.com/junedomingo/react-native-rename) is working perfectly with android, though in ios, yep, there are files that are not modified (specific on this project)

**Comment by malashkevich** [comment]
Actually I'm using simple find/replace functionality of IDE. There are few places where you need to change name. You can find those places by searching text `akveo.kittentricks`.
Also don't forget to change name in `android/app/src/main/values/strings.xml` and `ios/kittenTricks/Info.plist`

**Comment by malashkevich** [comment]
I'll close this issue. If you need more details - do not hesitate to reopen it.

**Comment by karthikcodes6** [comment]
Is it still valid now? or else should I change any other place?
